#!/usr/bin/env bash
#prints number of lines

echo " --- --- main --- ---"
cloc --by-file --unix --include-ext=go --exclude-dir=apps,resources,sdk .

echo " --- --- apps --- ---"
cloc --by-file --unix --include-ext=go --not-match-f="main.go" apps

