#!/usr/bin/env bash
#prints number of lines

echo " --- --- main --- ---"
cloc --by-file --unix --include-ext=go --exclude-dir=fonts,temp,tools,widgets,services .

echo " --- --- widgets --- ---"
cloc --by-file --unix --include-ext=go tools

