#!/usr/bin/env bash

START=$(date +%s);

echo "base"
(cp sdk.go base/sdk.go;cp sdk_wasi.go base/sdk_wasi.go;cd base;sh build;rm sdk.go;rm sdk_wasi.go;cd ../../) & 

echo "7gui"
(cp sdk.go 7gui/sdk.go;cp sdk_wasi.go 7gui/sdk_wasi.go;cd 7gui;sh build;rm sdk.go;rm sdk_wasi.go;cd ../../ ) &

echo "calendar"
(cp sdk.go calendar/sdk.go;cp sdk_wasi.go calendar/sdk_wasi.go;cd calendar;sh build;rm sdk.go;rm sdk_wasi.go;cd ../../ ) &

echo "map"
(cp sdk.go map/sdk.go;cp sdk_wasi.go map/sdk_wasi.go;cd map;sh build;rm sdk.go;rm sdk_wasi.go;cd ../../ ) &

echo "db"
(cp sdk.go db/sdk.go;cp sdk_wasi.go db/sdk_wasi.go;cd db;sh build;rm sdk.go;rm sdk_wasi.go;cd ../../ ) &

wait
END=$(date +%s);
echo $((END-START)) | awk '{print "Compiled in "int($1/60)"min "int($1%60)"sec"}'
